extend = "../Makefile.toml"

[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and then run cargo build and test"
category = "Development"
dependencies = [
  "format-toml-conditioned-flow",
  "format-flow",
  "clippy-flow",
  "pre-build",
  "build",
  "post-build",
  "services-up",
  "test-flow",
  "services-down",
]

[tasks.test]
env = { "POSTGRES_DB" = "primitives" }

[tasks.services-up]
script = "docker-compose -f ../docker-compose.yml up -d adex-postgres && sleep 6"

[tasks.services-down]
script = "docker-compose -f ../docker-compose.yml down"
