[workspace]

members = [
    "primitives",
    "adapter",
    "adview-manager",
    "validator_worker",
    "sentry",
    "test_harness",
]

[patch.crates-io]
postgres-types = { git = "https://github.com/elpiel/rust-postgres", branch = "boxed-dyn-ToSql"}