version: '3.8'

services:
  adex-postgres:
    build: ./scripts/postgres
    image: adex-postgres
    container_name: adex-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: 'localhost'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_MULTIPLE_DATABASES: harness_leader,harness_follower,sentry_leader,primitives
    networks:
      - adex-external

  adex-redis:
    image: redis
    container_name: adex-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - adex-external
  ganache-1:
    build:
      context: ./scripts/ethereum
      args:
        SNAPSHOT_CONTRACTS: snapshot_contracts_1
    image: adex-ganache
    container_name: adex-ganache-cli-chain_id-1
    restart: always
    ports:
      - "8545:8545"
    environment:
      CHAIN_ID: 1
    networks:
      - adex-external
  # Chain Id 1337 - the default Ganache chain id
  ganache-1337:
    build:
      context: ./scripts/ethereum
      args:
        SNAPSHOT_CONTRACTS: snapshot_contracts_1337
    image: adex-ganache
    container_name: adex-ganache-cli-chain_id-1337
    restart: always
    ports:
      # use a different port for this second instance of ganache-cli
      - "1337:8545"
    environment:
      CHAIN_ID: 1337
    networks:
      - adex-external

networks:
  adex-external: