# Builder
FROM rust:1.48.0 as builder

LABEL maintainer="dev@adex.network"

WORKDIR /usr/src/app

# An hack that build step will cache your dependencies

RUN mkdir -p primitives/src/ adapter/src/ sentry/src/

COPY ./primitives/Cargo.toml ./primitives/Cargo.toml
RUN touch ./primitives/src/lib.rs && echo "pub fn main() {println!(\"cargo:rerun-if-changed=\\\"/tmp/<projectname>/build.rs\\\"\");}" >> ./primitives/src/lib.rs

COPY ./adapter/Cargo.toml ./adapter/Cargo.toml
RUN touch ./adapter/src/lib.rs && echo "pub fn main() {println!(\"cargo:rerun-if-changed=\\\"/tmp/<projectname>/build.rs\\\"\");}" >> ./adapter/src/lib.rs

COPY ./sentry/Cargo.toml ./sentry/Cargo.toml
RUN touch ./sentry/src/main.rs && echo "fn main() {println!(\"cargo:rerun-if-changed=\\\"/tmp/<projectname>/build.rs\\\"\");}" >> ./sentry/src/main.rs

COPY ./Cargo.lock ./Cargo.lock
RUN touch Cargo.toml && echo "[workspace]\n members = [ 'primitives', 'adapter', 'sentry' ]" >> Cargo.toml

RUN cargo build -p sentry --release

# remove the not needed artifacts
RUN rm -f target/release/deps/sentry*
RUN rm -f target/release/deps/adapter*
RUN rm -f target/release/deps/primitives*
RUN rm -f target/release/deps/libadapter*
RUN rm -f target/release/deps/libprimitives*

COPY . .

# We install the sentry binary with all features in Release mode
# Inlcude the full backtrace for easier debugging

RUN RUST_BACKTRACE=full cargo install --path sentry --all-features

WORKDIR /usr/local/bin

RUN cp $CARGO_HOME/bin/sentry .

FROM ubuntu:20.04

RUN apt update && apt-get install -y libssl-dev ca-certificates

# `ethereum` or `dummy`
ENV ADAPTER=

# only applicable if you use the `--adapter ethereum`
ENV KEYSTORE_FILE=
ENV KEYSTORE_PWD=

# Only applicable if you use the `--adapter dummy`
ENV DUMMY_IDENTITY=

# If set it will override the configuration file used
ENV CONFIG=

WORKDIR /usr/local/bin

COPY docs/config/cloudflare_origin.crt /usr/local/share/ca-certificates/

RUN update-ca-certificates

COPY --from=builder /usr/local/bin/sentry .
RUN mkdir scripts
COPY  ./scripts ./scripts

ENTRYPOINT ["./scripts/entrypoint.sh"]

CMD sentry -a ${ADAPTER:-ethereum} \
            ${KEYSTORE_FILE:+-k $KEYSTORE_FILE} \
            ${DUMMY_IDENTITY:+-i $DUMMY_IDENTITY} \
            ${CONFIG}
