version: '3.8'

services:
  mongo-express:
    image: mongo-express
    container_name: adex-mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:mongodb@adex-mongodb:27017/
    networks:
      - adex-external