version: '3.8'

x-postgres-configuration: &postgres
  POSTGRES_USER: 'adex'
  POSTGRES_HOST: 'postgres'
  POSTGRES_PASSWORD: 'postgres'

services:
  # Service: Postgres
  postgres-leader:
    image: postgres
    container_name: adex-postgres-leader
    restart: always
    ports:
      - "5432:5432"
    # volumes: $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'adex'
      POSTGRES_HOST: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'sentry_leader'
    networks:
      - adex-leader
      - adex-external

  redis-leader:
    image: redis
    container_name: adex-redis-leader
    restart: always
    ports:
      - "6379:6379"
    networks:
      - adex-leader
      - adex-external

  ganache:
    build: ./scripts/ethereum
    image: adex-adapter-ganache
    container_name: adex-ganache-cli
    ports:
      - "8545:8545"
    networks:
      - adex-leader
      - adex-external

networks:
  adex-leader:
    internal: true
  adex-external:
