[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and than run cargo build and test"
category = "Development"
dependencies = [
  "format-flow",
  "format-toml-conditioned-flow",
  "pre-build",
  "build",
  "post-build",
  "local-test-flow",
]

[tasks.local-test-flow]
dependencies = ["services-up", "test-flow", "services-down"]


[tasks.services-up]
# `--renew-anon-volumes` will force the recreation of the services
# it's used primarily for `ganache-cli`.
# This forces the snapshot from previous unsuccessful test runs to get destroyed.
script = '''
docker-compose -f ../docker-compose.ci.yml up --renew-anon-volumes -d ganache redis-leader postgres-leader \
&& sleep 10
'''

[tasks.services-down]
script = "docker-compose -f ../docker-compose.ci.yml down"
