extend = "../Makefile.toml"

[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and then run cargo build and test"
category = "Development"
dependencies = [
  "format-toml-conditioned-flow",
  "format-flow",
  "clippy-flow",
  "pre-build",
  "build",
  "post-build",
  "local-test-flow",
]

[tasks.local-test-flow]
dependencies = ["services-up", "test-flow", "services-down"]

[tasks.services-up]
# `--renew-anon-volumes` will force the recreation of the services
# it's used primarily for `ganache-cli`.
# This forces the snapshot from previous unsuccessful test runs to get destroyed.
script = '''
docker-compose -f ../docker-compose.yml up --renew-anon-volumes -d ganache-1 ganache-1337 adex-redis adex-postgres \
&& sleep 6
'''

[tasks.services-down]
script = "docker-compose -f ../docker-compose.yml down"
