[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and than run cargo build and test"
category = "Development"
dependencies = [
  "format-flow",
  "format-toml-conditioned-flow",
  "pre-build",
  "build",
  "post-build",
  "local-test-flow"
]

[tasks.local-test-flow]
dependencies = [
  "services-up",
  "test-flow",
  "services-down",
]


[tasks.services-up]
script = '''
docker-compose -f ../docker-compose.ci.yml up -d ganache redis-leader postgres-leader \
&& sleep 10
'''

[tasks.services-down]
script = "docker-compose -f ../docker-compose.ci.yml down"
