# Maximum number of channels to return per request
max_channels = 512

channels_find_limit = 200
campaigns_find_limit = 200
spendable_find_limit = 200
wait_time = 500

msgs_find_limit = 10
analytics_find_limit = 5000
# in milliseconds
analytics_maxtime = 20000

heartbeat_time = 30000
health_threshold_promilles = 950
health_unsignable_promilles = 750
propagation_timeout = 1000

fetch_timeout = 5000
all_campaigns_timeout = 5000
channel_tick_timeout = 5000

ip_rate_limit = { type = 'ip', timeframe = 1200000 }
sid_rate_limit = { type = 'sid', timeframe = 0 }

creators_whitelist = []
validators_whitelist = []
# Leader - 0x80690751969B234697e9059e04ed72195c3507fa
admins = ['0x80690751969B234697e9059e04ed72195c3507fa']

# Ethereum mainnet tokens
# [chain."Ganache #1"]
# # Ethereum Mainnet for testing
# chain_id = 1
# rpc = 'http://localhost:8546'
# # Ganache Snapshot address
# outpace = '0x0000000000000000000000000000000000000000'
# # Ganache Snapshot address
# sweeper = '0x0000000000000000000000000000000000000000'

#     [chain."Ganache #1".token."Mocked TOKEN"]
#     address = '0x2bcaf6968aec8a3b5126fbfab5fd419da6e8ad8e' # checked
#     precision = 18
#     # Minimum token units for the Create2 deposits to count
#     # 1 * 10^18 = 1.0000 TOKEN
#     min_token_units_for_deposit = '1000000000000000000'
#     # multiplier = 10^12 - 10^18 (token precision) = 10^-6
#     # min_validator_fee = 1 * 10^-6 = 0.000_001
#     min_validator_fee = '1000000000000'

[chain."Ganache #1337"]
# Ganache default chain id for testing
chain_id = 1337
rpc = 'http://localhost:8545'
# Ganache Snapshot address
outpace = '0xAbc27d46a458E2e49DaBfEf45ca74dEDBAc3DD06'
# Ganache Snapshot address
sweeper = '0x7dD57C0324284102A757153E18F2Cb1ACdB7d2bD'

    [chain."Ganache #1337".token."Mocked TOKEN"]
    address = '0x2bcaf6968aec8a3b5126fbfab5fd419da6e8ad8e' # checked
    precision = 18
    # Minimum token units for the Create2 deposits to count
    # 1 * 10^18 = 1.0000 TOKEN
    min_token_units_for_deposit = '1000000000000000000'
    # multiplier = 10^12 - 10^18 (token precision) = 10^-6
    # min_validator_fee = 1 * 10^-6 = 0.000_001
    min_validator_fee = '1000000000000'

    [chain."Ganache #1337".token."Mocked TOKEN 2"]
    address = '0x0000000000000000000000000000000000000000' # checked
    precision = 18
    # Minimum token units for the Create2 deposits to count
    # 1 * 10^18 = 1.0000 TOKEN
    min_token_units_for_deposit = '1000000000000000000'
    # multiplier = 10^12 - 10^18 (token precision) = 10^-6
    # min_validator_fee = 1 * 10^-6 = 0.000_001
    min_validator_fee = '1000000000000'

