# Maximum number of channels to return per request
max_channels = 512

channels_find_limit = 512
campaigns_find_limit = 512
spendable_find_limit = 512

wait_time = 40000

# V4 Deprecated
aggr_throttle = 0

events_find_limit = 100

msgs_find_limit = 10
analytics_find_limit_v5 = 5000
analytics_maxtime_v5 = 15000

heartbeat_time = 60000
health_threshold_promilles = 970
health_unsignable_promilles = 770
propagation_timeout = 3000

fetch_timeout = 10000
all_campaigns_timeout = 10000
channel_tick_timeout = 10000

ip_rate_limit = { type = 'ip', timeframe = 1200000 }
sid_rate_limit = { type = 'sid', timeframe = 0 }

# TODO: Replace with real contract address
outpace_address = '0x333420fc6a897356e69b62417cd17ff012177d2b'
# TODO: Replace with real contract address
sweeper_address = '0x333420fc6a897356e69b62417cd17ff012177d2b'

ethereum_network = 'http://localhost:8545'
ethereum_adapter_relayer = 'https://relayer.adex.network'

creators_whitelist = []
validators_whitelist = []


[[token_address_whitelist]]
# DAI
address = '0x6b175474e89094c44da98b954eedeac495271d0f'
# 1 * 10^-10 = 0.0_000_000_001
min_token_units_for_deposit = '100000000'
min_validator_fee = '100000000'
precision = 18

[[token_address_whitelist]]
# SAI
address = '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359'
# 1 * 10^-10 = 0.0_000_000_001
min_token_units_for_deposit = '100000000'
min_validator_fee = '100000000'
precision = 18

[[token_address_whitelist]]
# USDT
address = '0xdac17f958d2ee523a2206206994597c13d831ec7'
# 1.000_000
min_token_units_for_deposit = '1000000'
# 0.001
min_validator_fee = '1000'
precision = 6

[[token_address_whitelist]]
# USDC
address = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'
# 1.000_000
min_token_units_for_deposit = '100000000'
# 0.001
min_validator_fee = '1000'
precision = 6
