# Maximum number of channels to return per request
max_channels = 512

channels_find_limit = 512
campaigns_find_limit = 512
spendable_find_limit = 512
wait_time = 40000

msgs_find_limit = 10
analytics_find_limit = 5000
# in milliseconds
analytics_maxtime = 15000

heartbeat_time = 60000
health_threshold_promilles = 970
health_unsignable_promilles = 770
propagation_timeout = 3000

fetch_timeout = 10000
all_campaigns_timeout = 10000
channel_tick_timeout = 10000

ip_rate_limit = { type = 'ip', timeframe = 1200000 }
sid_rate_limit = { type = 'sid', timeframe = 0 }

creators_whitelist = []
validators_whitelist = []
admins = ['0x5d6A3F1AD7b124ecDFDf4841D9bB246eD5fBF04c']

[[token_address_whitelist]]
# DAI
# Polygon: https://polygonscan.com/token/0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063
address = '0x6b175474e89094c44da98b954eedeac495271d0f'
# 1 * 10^-10 = 0.0_000_000_001
min_campaign_budget = '100000000'
min_validator_fee = '100000000'
precision = 18

[[token_address_whitelist]]
# SAI
address = '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359'
# 1 * 10^-10 = 0.0_000_000_001
min_campaign_budget = '100000000'
min_validator_fee = '100000000'
precision = 18

[[token_address_whitelist]]
# USDT
# Polygon: https://polygonscan.com/token/0xc2132d05d31c914a87c6611c10748aeb04b58e8f
address = '0xdac17f958d2ee523a2206206994597c13d831ec7'
# 1.000_000
min_campaign_budget = '1000000'
# 0.001
min_validator_fee = '1000'
precision = 6

[[token_address_whitelist]]
# USDC
# Polygon: https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174
address = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'
# 1.000_000
min_campaign_budget = '100000000'
# 0.001
min_validator_fee = '1000'
precision = 6
