[package]
name = "adapter-v3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = {path = "../primitives", features = ["test-util"] }
