[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and than run cargo build and test"
category = "Development"
dependencies = [
  "format-flow",
  "format-toml-conditioned-flow",
  "pre-build",
  "build",
  "post-build",
  "ganache-up",
  "test-flow",
  "ganache-down",
]

[tasks.ganache-up]
script = '''
docker-compose -f ../docker-compose.harness.yml up --renew-anon-volumes -d ganache \
&& sleep 10
'''

[tasks.ganache-down]
script = "docker-compose -f ../docker-compose.harness.yml down"
