extend = "../Makefile.toml"

[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and than run cargo build and test"
category = "Development"
dependencies = [
  "format-toml-conditioned-flow",
  "format-flow",
  "clippy-flow",
  "pre-build",
  "build",
  "post-build",
  "ganache-up",
  "test-flow",
  "ganache-down",
]

[tasks.test]
args = ["test", "--all-features"]

[tasks.ganache-up]
# `--renew-anon-volumes` is required to make sure that the snapshot used for the `ganache` instances is reloaded.
script = '''
docker-compose -f ../docker-compose.yml up --renew-anon-volumes -d ganache-1 ganache-1337 \
&& sleep 6
'''

[tasks.ganache-down]
script = "docker-compose -f ../docker-compose.yml down"
