on: [push, pull_request]

name: Continuous Integration

jobs:
  ci-flow:
    name: cargo make ci-flow - Tests, clippy & rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # Runs all services needed for testing
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          # https://docs.docker.com/compose/reference/overview/
          cli-args: "-f docker-compose.harness.yml up -d"
      - uses: actions-rs/toolchain@v1
        with:
          # No need to add `toolchain`, it will use `rust-toolchain` file instead
          profile: default
          override: true
          components: clippy, rustfmt
      - uses: davidB/rust-cargo-make@v1
      - name: Run `cargo make ci-flow`
        # Running cargo make doesn't successfully start `ganache`
        run: |
          cargo make ci-flow
        # set environment variables for `primitives` postgres tests
        env:
          POSTGRES_DB: sentry_leader
