on:
  push:
    branches:
      - aip-61-adex-v5

name: Deploy docs

jobs:
  deploy-docs:
    name: Deploy docs on gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          # Use nightly to build the docs with `--cfg docsrs`
          toolchain: nightly
          profile: minimal
          components: rust-docs
      - name: Build docs
        # Building locally:
        # for `--enable-index-page` it is required to pass `-Z unstable-options` to rustdocs
        run: RUSTDOCFLAGS="--cfg docsrs -Z unstable-options --enable-index-page" cargo +nightly doc --all-features --no-deps --workspace
      - name: Prepare /docs
        run: |
          rm -rf ./docs
          mv target/doc ./docs
      - name: Deploy gh-pages
        # if: github.ref == 'refs/heads/aip-61-adex-v5'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
