on:
  push:
    branches:
      - aip-61-adex-v5

name: Deploy docs

jobs:
  deploy-docs:
    name: Deploy docs on gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build docs
        run: cargo doc --no-deps
      - name: Prepare /docs & index file
        run: |
          rm -rf ./docs
          echo "<meta http-equiv=\"refresh\" content=\"0; url=sentry\">" > target/doc/index.html
          cp -r target/doc ./docs
      - name: Deploy gh-pages
        # if: github.ref == 'refs/heads/aip-61-adex-v5'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
